In [1]:
import pandas as pd 
import numpy as np

In [2]:
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)

In [3]:
df = pd.read_csv("gurgaon_properties.csv")

In [4]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2284,4 Bedroom House for sale in Sector 48 Gurgaon,house,vipul tatvam villa,8.40,21000.0,4000.0,Plot area 4000(371.61 sq.m.),4,5,3+,"pooja room,study room,servant room","Sector 48 Gurgaon, Gurgaon, Haryana",2.0,North,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Wishing to settle down in an individual house ...,"['5 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2887,3 BHK Flat in Sector 104 Gurgaon,flat,godrej summit,1.05,5833.0,1800.0,Carpet area: 1800 (167.23 sq.m.),3,4,3+,servant room,"Sector 104 Gurgaon, Gurgaon, Haryana",7.0,East,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",Godrej summit society is resort like society h...,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4.5 out of 5', 'Construction4 out ..."
1949,2 Bedroom House for sale in Ashok Vihar Phase 3,house,independent,0.50,5555.0,900.0,Plot area 900(83.61 sq.m.),2,1,2,store room,"Ashok Vihar Phase 3, Gurgaon, Haryana",1.0,NaN,10+ Year Old,NaN,"Independent house, near to main road. Near by ...","['1 Wardrobe', '3 Light', 'No AC', 'No Bed', '...","['Natural Light', 'Airy Rooms']",NaN
1767,5 Bedroom House for sale in DLF Phase 2,house,independent,NaN,NaN,NaN,Plot area 502(419.74 sq.m.)Built Up area: 450 ...,5,5,3+,"pooja room,study room,servant room,others","Dlf Phase 2, DLF Phase 2, Gurgaon, Haryana",2.0,West,1 to 5 Year Old,"['Vodafone belvedere towers metro station', 'D...",Dlf phase 2 very prime location. This villa we...,"['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
3545,4 BHK Flat in Sector 50 Gurgaon,flat,elevate,6.75,19882.0,3395.0,Built Up area: 3395 (315.41 sq.m.),4,4,0,not available,"Sector 50, Sector 50 Gurgaon, Gurgaon, Haryana",10.0,NaN,undefined,NaN,Best in class property available at sector 50 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [5]:
df.shape

(3961, 20)

In [6]:
df.duplicated().sum()

0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [8]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Nirvana Country,flat,the close north,2.35,11767.0,1997.0,Super Built up area 1997(185.53 sq.m.)Built Up...,3,3,3+,not available,"8/9, Nirvana Country, Gurgaon, Haryana",8.0,North-East,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","Situated in nirvana country, gurgaon, the clos...","['5 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
1,3 BHK Flat in Sector 109 Gurgaon,flat,ats tourmaline,2.30,8897.0,2585.0,Super Built up area 2585(240.15 sq.m.),3,4,3+,"servant room,others","Flat Number 2101, 10th Floor, Tower 2, Sector ...",10.0,East,0 to 1 Year Old,"['Dwarka Sector 21 Metro Station', 'NeoSquare ...",Residential apartment for sell.Located on 10th...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
2,3 Bedroom House for sale in Nirvana Country,house,unitech espace,7.50,34722.0,2160.0,Plot area 240(200.67 sq.m.)Built Up area: 241 ...,3,3,2,servant room,"240 Yards Espace Nirvana Country Villa, Nirvan...",2.0,West,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",Available for sale 240 yards simplex villa in ...,"['1 Exhaust Fan', '4 Geyser', '1 Stove', '1 Mi...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,2 BHK Flat in Sector-35 Sohna,flat,hcbs sports ville,0.27,3600.0,750.0,Super Built up area 750(69.68 sq.m.)Carpet are...,2,2,2,not available,"Sector-35 Sohna, Gurgaon, Haryana",2.0,North-East,0 to 1 Year Old,NaN,North-East facing ready-To-Move-In flat with b...,"['1 Exhaust Fan', '1 Geyser', '1 Modular Kitch...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety5 out of 5', 'Lifestyle4 out of 5', 'E..."
4,4 BHK Flat in Cyber City,flat,dlf 3 apartment,2.50,7142.0,3500.0,Super Built up area 3500(325.16 sq.m.),4,4,3+,"pooja room,study room,servant room","U 27/7, Cyber City, Gurgaon, Haryana",2.0,North-West,10+ Year Old,"['Vodafone belvedere towers metro station', 'I...",4 master bedroom attached washroom and balconi...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Security Personnel', 'Internet/wi-fi connect...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [9]:
df.insert(loc = 3, column="sector" , value = df["property_name"].str.split("in").str.get(1).str.replace("Gurgaon","").str.strip())

In [10]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Nirvana Country,flat,the close north,Nirvana Country,2.35,11767.0,1997.0,Super Built up area 1997(185.53 sq.m.)Built Up...,3,3,3+,not available,"8/9, Nirvana Country, Gurgaon, Haryana",8.0,North-East,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","Situated in nirvana country, gurgaon, the clos...","['5 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
1,3 BHK Flat in Sector 109 Gurgaon,flat,ats tourmaline,Sector 109,2.30,8897.0,2585.0,Super Built up area 2585(240.15 sq.m.),3,4,3+,"servant room,others","Flat Number 2101, 10th Floor, Tower 2, Sector ...",10.0,East,0 to 1 Year Old,"['Dwarka Sector 21 Metro Station', 'NeoSquare ...",Residential apartment for sell.Located on 10th...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
2,3 Bedroom House for sale in Nirvana Country,house,unitech espace,Nirvana Country,7.50,34722.0,2160.0,Plot area 240(200.67 sq.m.)Built Up area: 241 ...,3,3,2,servant room,"240 Yards Espace Nirvana Country Villa, Nirvan...",2.0,West,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",Available for sale 240 yards simplex villa in ...,"['1 Exhaust Fan', '4 Geyser', '1 Stove', '1 Mi...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,2 BHK Flat in Sector-35 Sohna,flat,hcbs sports ville,Sector-35 Sohna,0.27,3600.0,750.0,Super Built up area 750(69.68 sq.m.)Carpet are...,2,2,2,not available,"Sector-35 Sohna, Gurgaon, Haryana",2.0,North-East,0 to 1 Year Old,NaN,North-East facing ready-To-Move-In flat with b...,"['1 Exhaust Fan', '1 Geyser', '1 Modular Kitch...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety5 out of 5', 'Lifestyle4 out of 5', 'E..."
4,4 BHK Flat in Cyber City,flat,dlf 3 apartment,Cyber City,2.50,7142.0,3500.0,Super Built up area 3500(325.16 sq.m.),4,4,3+,"pooja room,study room,servant room","U 27/7, Cyber City, Gurgaon, Haryana",2.0,North-West,10+ Year Old,"['Vodafone belvedere towers metro station', 'I...",4 master bedroom attached washroom and balconi...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Security Personnel', 'Internet/wi-fi connect...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [11]:
df["sector"] = df["sector"].str.lower()

In [12]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Nirvana Country,flat,the close north,nirvana country,2.35,11767.0,1997.0,Super Built up area 1997(185.53 sq.m.)Built Up...,3,3,3+,not available,"8/9, Nirvana Country, Gurgaon, Haryana",8.0,North-East,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","Situated in nirvana country, gurgaon, the clos...","['5 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
1,3 BHK Flat in Sector 109 Gurgaon,flat,ats tourmaline,sector 109,2.30,8897.0,2585.0,Super Built up area 2585(240.15 sq.m.),3,4,3+,"servant room,others","Flat Number 2101, 10th Floor, Tower 2, Sector ...",10.0,East,0 to 1 Year Old,"['Dwarka Sector 21 Metro Station', 'NeoSquare ...",Residential apartment for sell.Located on 10th...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
2,3 Bedroom House for sale in Nirvana Country,house,unitech espace,nirvana country,7.50,34722.0,2160.0,Plot area 240(200.67 sq.m.)Built Up area: 241 ...,3,3,2,servant room,"240 Yards Espace Nirvana Country Villa, Nirvan...",2.0,West,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",Available for sale 240 yards simplex villa in ...,"['1 Exhaust Fan', '4 Geyser', '1 Stove', '1 Mi...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment5 out of 5', 'Safety5 out of 5', ..."
3,2 BHK Flat in Sector-35 Sohna,flat,hcbs sports ville,sector-35 sohna,0.27,3600.0,750.0,Super Built up area 750(69.68 sq.m.)Carpet are...,2,2,2,not available,"Sector-35 Sohna, Gurgaon, Haryana",2.0,North-East,0 to 1 Year Old,NaN,North-East facing ready-To-Move-In flat with b...,"['1 Exhaust Fan', '1 Geyser', '1 Modular Kitch...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety5 out of 5', 'Lifestyle4 out of 5', 'E..."
4,4 BHK Flat in Cyber City,flat,dlf 3 apartment,cyber city,2.50,7142.0,3500.0,Super Built up area 3500(325.16 sq.m.),4,4,3+,"pooja room,study room,servant room","U 27/7, Cyber City, Gurgaon, Haryana",2.0,North-West,10+ Year Old,"['Vodafone belvedere towers metro station', 'I...",4 master bedroom attached washroom and balconi...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Security Personnel', 'Internet/wi-fi connect...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [13]:
df["sector"].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 90                                                     90
sector 65                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 95                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
sector 70                                                     53
nirvana country                                               53
sector 37c                                                    53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 2                                                   43
dlf phase 1                                                   43
sector 113                                                    43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 54                                                     27
laxman vihar                                                  27
sector 71                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
dlf phase 3                                                   22
sector 111                                                    22
sector 67a                                                    22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 62                                                     17
sector 91                                                     17
sector 99                                                     16
sector 110                                                    16
sushant lok phase 3                                           16
sector 14                                                     15
sector 60                                                     15
sector 63                                                     15
sector 76                                                     14
sector 3                                                      14
sector 52                                                     14
dlf phase 5                                                   14
gwal pahari                                                   14
sector 53                                                     14
sector 1 imt manesar                                          14
rajendra park                                                 14
sector 46                                                     13
laxman vihar phase 2                                          13
sector 36a                                                    13
sector 93                                                     12
sohna road                                                    12
sector 31                                                     12
uppals southend                                               12
sector 39                                                     12
sector 38                                                     12
sector 50                                                     12
sector 9a                                                     11
sector 47                                                     11
ashok vihar phase 3 extension                                 11
sector 7                                                      10
sector 1a imt manesar                                         10
south city 1                                                   9
sector 95a                                                     9
sector 55                                                      9
ashok vihar phase 2                                            9
sector 4                                                       9
palam vihar extension                                          8
c block sushant lok phase 1                                    8
mehrauli  road                                                 8
sector 40                                                      8
dwarka expressway                                              8
sector 89 a                                                    8
sector 43                                                      8
malibu town                                                    8
sector 59                                                      8
sector 57                                                      8
sector 10a                                                     8
sector 51                                                      7
sector 26                                                      7
sector 36 sohna                                                7
mianwali colony                                                7
surat nagar 1                                                  7
new colony                                                     7
sector 11                                                      7
sector 58                                                      7
sector 5                                                       6
sector 1                                                       6
jacobpura                                                      6
ashok vihar                                                    6
jyoti park                                                     6
rajiv nagar                                                    6
sector 2                                                       5
ansal plaza                                                    5
chakkarpur                                                     5
sector 28                                                      5
sector 23a                                                     5
manesar                                                        5
sector 9                                                       5
dayanand colony                                                5
sector 105                                                     5
sector 30                                                      5
subhash nagar                                                  5
new palam vihar                                                5
saraswati vihar                                                5
sushant lok phase 2                                            5
arjun nagar                                                    5
greenwood city                                                 5
sector 80                                                      5
shivaji nagar                                                  4
sector 12a                                                     4
sector 3a                                                      4
sector 12                                                      4
surya vihar                                                    4
adarsh nagar                                                   4
sector 45                                                      4
dharam colony                                                  4
ravi nagar                                                     4
suncity                                                        4
bhondsi                                                        4
sector 17                                                      4
sector 36                                                      4
shivpuri                                                       4
sector 6                                                       4
devilal colony                                                 4
bhim nagar                                                     4
baldev nagar                                                   4
vishnu garden                                                  4
garhi harsaru                                                  4
new                                                            4
imt manesar                                                    4
krishna colony                                                 4
madanpuri                                                      4
valley view estate                                             4
sector 17a                                                     3
sector 23                                                      3
sector 110 a                                                   3
prem nagar                                                     3
sector 15                                                      3
laxmi garden                                                   3
shakti nagar                                                   3
gandhi nagar                                                   3
sector 27                                                      3
sector 88b                                                     3
sector 73                                                      3
patel nagar                                                    3
a block sushant lok phase 1                                    3
sector 8                                                       3
mg road                                                        3
maruti kunj                                                    3
b block sushant lok phase 1                                    3
sector 17b                                                     3
sushant lok                                                    2
ambience island                                                2
samaspur                                                       2
sector 15 part 1                                               2
hira nagar                                                     2
pratap nagar                                                   2
sector 21                                                      2
lajpat nagar                                                   2
acharya puri                                                   2
bissar                                                         2
sheetla colony                                                 2
sohna  road                                                    2
shanti nagar                                                   2
shankar vihar                                                  2
new basti                                                      2
mohan nagar                                                    2
, delhi ncr                                                    2
sector-11 sohna                                                2
golf course ext road                                           2
sector-2 sohna                                                 2
iffco chowk                                                    2
block a surya vihar                                            2
west rajiv nagar                                               2
bhawani enclave                                                2
rosewood                                                       2
sector 32                                                      2
surat nagar                                                    2
faridabad road                                                 2
sector 41                                                      2
new palam vihar phase 1                                        2
sector 15 part 2                                               2
new palam vihar phase 2                                        2
sector 24                                                      2
surat nagar phase 2                                            2
golf course road                                               2
sispal vihar                                                   2
rajiv chowk                                                    2
manohar nagar                                                  2
daulatabad                                                     2
nars                                                           2
mayfield garden                                                2
farukhnagar                                                    2
alipur                                                         1
rajiv colony                                                   1
cyber city                                                     1
saraswati enclave                                              1
near sector 1 market                                           1
ram nagar                                                      1
south city                                                     1
sec 3 bhim vihar part 1 bhimgher kheri                         1
sector 5 chowk                                                 1
new colony, sector 7                                           1
near nand hospital                                             1
bhora kalan                                                    1
sector 4 urban estate                                          1
gopal nagar, garhi ghasita, sonipat                            1
garauli kalan                                                  1
sector 42                                                      1
vir nagar                                                      1
sector-5 sheetla colony                                        1
ravi nager basai road                                          1
civil l                                                        1
sector 37a                                                     1
sector-7 hous                                                  1
bhimgarh kheri phase 3                                         1
sector-35 sohna                                                1
tekchand nagar                                                 1
near pataudi chowk                                             1
ats marigold                                                   1
huda saraswati vihar                                           1
hno 13 sagar enclave sura                                      1
saroop garden rajendra park                                    1
laxmna vihar, phase 2                                          1
lucknow                                                        1
om nagar                                                       1
ansal's palam vihar                                            1
near khandsa road                                              1
khandsa                                                        1
begampur khatola                                               1
shivji park colony                                             1
pataudi road                                                   1
hsiidc plot sector 1 imt manesar                               1
block g sector-57                                              1
kheri                                                          1
sadar bazar                                                    1
ashok vihar phase i                                            1
old delhi road, opp sector-14                                  1
sector 37b                                                     1
kanahi                                                         1
b1 block sector 57                                             1
sai kunj                                                       1
devi lal colony gali no 12 gurgaon nr omkar public school      1
g block dlf city phase 1                                       1
sector 21a faridabad                                           1
damdma                                                         1
mahalaxmi garden, rajendra place                               1
part 3 sector 5                                                1
sector 13                                                      1
sultanpur                                                      1
anand garden, sector-105                                       1
laxman vihar, railway road,                                    1
nirvana country pocket h                                       1
udyog vihar phase 1                                            1
bptp                                                           1
heritage city                                                  1
near euro                                                      1
sector 9b                                                      1
ashok vihar phase 3                                            1
v block dlf phase 3                                            1
sector 17c                                                     1
block h ashok vihar phase iii extension                        1
jacobpura near sadar bazar                                     1
jat colony,fazilpur/taj nagar road                             1
godrej aria , sector 79 ,                                      1
dhankot                                                        1
naharpur rupa                                                  1
new jyoti park                                                 1
carterpuri village                                             1
sector-5 sohna                                                 1
park view                                                      1
urban estate, sector 5                                         1
mahavir pura                                                   1
rattan garden                                                  1
Name: count, dtype: int64

In [29]:
df["sector"] = df["sector"].str.replace("dharam colony","sector 12")
df["sector"] = df["sector"].str.replace("krishna colony","sector 7")
df["sector"] = df["sector"].str.replace("suncity","sector 54")
df["sector"] = df["sector"].str.replace("prem nagar","sector 13")
df["sector"] = df["sector"].str.replace("mg road","sector 28 ")
df["sector"] = df["sector"].str.replace("gandhi nagar","sector 28")
df["sector"] = df["sector"].str.replace("laxmi garden","sector 11")
df["sector"] = df["sector"].str.replace("sakti nagar","sector 11")

In [31]:

df["sector"] = df["sector"].str.replace('baldev nagar', 'sector 7')
df["sector"] = df["sector"].str.replace('shivpuri', 'sector 7')
df["sector"] = df["sector"].str.replace('garhi harsaru', 'sector, 17')
df["sector"] = df["sector"].str.replace('imt manesar','manesar')
df["sector"] = df["sector"].str.replace('adarsh nagar','sector 12')
df["sector"] = df["sector"].str.replace('shivaji nagar', 'sector 11')
df["sector"] = df["sector"].str.replace('bhim nagar','sector 6')
df["sector"] = df["sector"].str.replace('madanpuri','sector 7')
df["sector"] = df["sector"].str.replace('saraswati vihar','sector 28')
df["sector"] = df["sector"].str.replace('arjun nagar', 'sector 8')
df["sector"] = df["sector"].str.replace('ravi nagar', 'sector 9' )
df["sector"] = df["sector"].str.replace('vishnu garden', 'sector 105')
df["sector"] = df["sector"].str.replace('bhondsi', 'sector 11')
df["sector"] = df["sector"].str.replace('surya vihar', "sector 21")
df["sector"] = df["sector"].str.replace('devilal colony', 'sector 9')
df["sector"] = df["sector"].str.replace('valley view estate', 'gwal pahari')
df["sector"] = df["sector"].str.replace('mehrauli road', ' sector 14')
df["sector"] = df["sector"].str.replace('jyoti park', 'sector 7')
df["sector"] = df["sector"].str.replace("ansal plaza", "sector 23")
df["sector"] = df["sector"].str.replace("dayanand colony","sector 6")
df["sector"] = df["sector"].str.replace("sushant lok phase 2","sector 55")
df["sector"] = df["sector"].str.replace("chakkarpur ","sector 28")
df["sector"] = df["sector"].str.replace(' greenwood city',"sector 45")
df["sector"] = df["sector"].str.replace('subhash nagar' ,'sector 12')

In [32]:
df[ 'sector'] = df["sector"].str.replace('sohna road road', 'sohna road')
df[ 'sector'] = df["sector"].str.replace('malibu town', 'sector 47')
df[ 'sector'] = df["sector"].str.replace('surat nagar 1','sector 104')
df[ 'sector'] = df["sector"].str.replace(' new colony', 'sector 7')
df[ 'sector'] = df["sector"].str.replace('mianwali colony', 'sector 12')
df[ 'sector'] = df["sector"].str.replace("jacobpura", 'sector 12')
df[ 'sector'] = df["sector"].str.replace('rajiv nagar', 'sector 13')
df[ 'sector'] = df["sector"].str.replace('ashok vihar', 'sector 3')
df[ 'sector'] = df["sector"].str.replace('dlf phase 1', 'sector 26')
df[ 'sector'] = df["sector"].str.replace('nirvana country', 'sector 50')
df ['sector'] = df["sector"].str.replace('palam vihar', 'sector. 2')
df[ 'sector'] = df["sector"].str.replace('dlf: phase 2', 'sector 25')
df[ 'sector'] = df["sector"].str.replace('sushant lok phase 1', 'sector 43')
df[ 'sector'] = df["sector"].str.replace('laxman vihar', 'sector 4')
df[ 'sector'] = df["sector"].str.replace('dlf phase 4', 'sector 28') 
df["sector"]  = df["sector"].str.replace('dif phase 3', 'sector. 24')
df[ 'sector'] = df["sector"].str.replace('sushant lok phase 3', 'sector 57')
df[ 'sector'] = df["sector"].str.replace('dlf phase 5', 'sector 43')
df[ 'sector'] = df["sector"].str.replace('rajendra park','sector 105')
df['sector']  = df["sector"].str.replace('uppals southend', 'sector 49')
df['sector']  = df["sector"].str.replace('sohna','sohna road')
df[ 'sector'] = df["sector"].str.replace('ashok vihar phase 3 extension', 'sector 5')
df["sector"]  = df["sector"].str.replace('south city 1', 'sector 41')
df[ 'sector'] = df["sector"].str.replace('ashok vihar phase 2', 'sector 5')

In [43]:
a = df["sector"].value_counts()[df["sector"].value_counts() >=3]
df = df[df["sector"].isin(a.index)]

In [44]:
df["sector"].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 90                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 95                      57
sector 56                      57
sector 89                      56
sector 48                      56
sector 70a                     54
sector 70                      53
sector 37c                     53
sector 43                      53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector. 2                      50
sector 49                      48
sector 67                      48
sector 66                      46
sector 103                     45
sector 113                     43
dlf phase 2                    43
sector 61                      42
sector 82                      42
sector 28                      39
sector 106                     38
sector 4                       36
sector 7                       32
sector 99a                     32
sector 54                      31
sector 12                      30
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 57                      24
sector 112                     24
sector 88a                     23
sector 33                      23
sector 105                     23
sector 111                     22
dlf phase 3                    22
sector 67a                     22
sector 82a                     20
sector 3                       20
sector 22                      20
sector 47                      19
sector 78                      19
gwal pahari                    18
sector 63a                     18
sector 74                      18
sector 11                      18
sector 91                      17
sector 62                      17
sector 110                     16
sector 99                      16
sector 63                      15
sector 60                      15
sector 14                      15
sector 76                      14
sector 52                      14
sector 1 manesar               14
sector 53                      14
sector 55                      14
sector 9                       13
sector 4 phase 2               13
sector 6                       13
sector 46                      13
sector 36a                     13
sector 93                      12
sohna road road                12
sector 39                      12
sector 38                      12
sector 31                      12
sector 3 phase 3 extension     11
sector 41                      11
sector 9a                      11
sector 1a manesar              10
sector 13                      10
manesar                         9
sector 95a                      9
sector 3 phase 2                9
sector 23                       8
sector. 2 extension             8
sector 89 a                     8
sector 59                       8
sector 8                        8
c block sector 43               8
sector 10a                      8
dwarka expressway               8
sector 40                       8
mehrauli  road                  8
sector 58                       7
sector 51                       7
sector 36 sohna road            7
new colony                      7
sector 1                        6
sector 21                       6
sector 5                        6
new sector. 2                   5
chakkarpur                      5
sector 80                       5
sector 30                       5
sector 2                        5
sector 23a                      5
greenwood city                  5
sector 36                       4
sector 45                       4
sector 12a                      4
sector 3a                       4
sector 17                       4
new                             4
sector, 17                      4
sector 17a                      3
sector 110 a                    3
sector 17b                      3
sector 88b                      3
shakti nagar                    3
sector 27                       3
b block sector 43               3
sector 28                       3
a block sector 43               3
patel nagar                     3
maruti kunj                     3
sector 73                       3
sector 15                       3
Name: count, dtype: int64